id: I987866EF
legacy_id: P000721
ocr_import_info:
  bdrc_scan_id: W4CZ65571
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T00:41:05'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T20:56:06.159666+00:00'
last_modified: 2022-09-04 04:56:12.531332
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ65571
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ65571
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཀུན་བཟང་དགོངས་བཅུད་སྣང་སྲིད་ཞི་བ་ཆེན་མོའི་སྦྱིན་སྲེག
statistics:
  ocr_word_mean_confidence_index: 0.6022366078597314
  ocr_word_median_confidence_index: 0.6299999952316284
quality: null
bases:
  I4CZ65631:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ65631
      total_pages: 186
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4CZ65631.txt
    statistics:
      ocr_word_median_confidence_index: 0.6299999952316284
      ocr_word_mean_confidence_index: 0.6022366078597314
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
