id: P000721
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-16 16:38:59.017097
source_metadata:
  id: bdr:W4CZ65571
  title: ཀུན་བཟང་དགོངས་བཅུད་སྣང་སྲིད་ཞི་བ་ཆེན་མོའི་སྦྱིན་སྲེག
  author: ''
  volumes:
    8668638fcafe48999e4e82281b7349c2:
      image_group_id: I4CZ65631
      title: ''
      volume_number: 1
      total_pages: 186
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
