id: P000721
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ65571
  title: ཀུན་བཟང་དགོངས་བཅུད་སྣང་སྲིད་ཞི་བ་ཆེན་མོའི་སྦྱིན་སྲེག
  author: ''
  volumes:
    8668638fcafe48999e4e82281b7349c2:
      image_group_id: I4CZ65631
      title: ''
      volume_number: 1
      total_pages: 186
      base_file: v001.txt
